### ISSUE TITLE
Allow for switching sides of White and Black 

### ISSUE THREAD

**Issue by ericstraily** [Navisjon/uwh-refbox-rs#35]
**Is your feature request related to a problem? Please describe.**
Depending on the orientation of the display to the playing court it might make sense for white to be on the right or on the left and black on the opposite

**Describe the solution you'd like**
This should be editable some place the time/score keeper can access and not just in a config file. The display code needs to take in a parameter and display accordingly

**Comment by TristanDebrunner** [comment]
Fixed by #59
